#!/bin/sh
# DOWNLOAD_DATA_DIR must be set;

BASE_MLPERF_DIR=$GPUAPPS_ROOT/bin/$CUDA_VERSION/release/mlperf_inference/inference/
UNET_DIR=$BASE_MLPERF_DIR/vision/medical_imaging/3d-unet-brats19/

cd $UNET_DIR; . $BASE_MLPERF_DIR/virtual_environment/bin/activate; python run.py  --backend=pytorch --scenario=Offline --accuracy; deactivate;