#!/bin/sh
# DATA_DIR and MODEL_DIR must be set;

BASE_MLPERF_DIR=$GPUAPPS_ROOT/bin/$CUDA_VERSION/release/mlperf_inference/inference/
RESNET_DIR=$BASE_MLPERF_DIR/vision/classification_and_detection/

cd $RESNET_DIR; . $BASE_MLPERF_DIR/virtual_environment/bin/activate; export MODEL_DIR=$PWD; . run_local.sh pytorch resnet50 gpu --count 2048 --scenario Offline