#!/bin/sh

BASE_MLPERF_DIR=$GPUAPPS_ROOT/bin/$CUDA_VERSION/release/mlperf_inference/inference/
GNMT_DIR=$BASE_MLPERF_DIR/translation/gnmt/tensorflow

cd $GNMT_DIR ; . $BASE_MLPERF_DIR/virtual_environment_tensorflow_1_15/bin/activate; python -u run_task.py --run=performance --batch_size=32; deactivate;